DROP TABLE IF EXISTS "supplier";

DROP TABLE IF EXISTS "delivery";

DROP TABLE IF EXISTS "employee";

DROP TABLE IF EXISTS "order";

DROP TABLE IF EXISTS "client";

DROP TABLE IF EXISTS "dish";

DROP TABLE IF EXISTS "restaurant";
